### ISSUE TITLE
Can't get Jekyll to run

### ISSUE THREAD

**Issue by electronicdreamplant** [matteobrusa/Password-protection-for-static-pages#9]
This is a great bit of code for simple password protection but I'm struggling (n00b)

My Jekyll site worked fine before I moved it into the folder, now only non-jekyll pages work. I've tried moving the _config.yml and gem files to outside of the folder but that hasn't worked either. 

Repo is here: https://github.com/electronicdreamplant/memorybox3

**Comment by matteobrusa** [comment]
Unfortunately I'm no Jekyll expert, i suggest to see what's the error in the console.

**Comment by eyecatchup** [comment]
That's not an issue with Jekyll. @electronicdreamplant  You're loading a different SHA1 lib ([this](https://cdn.rawgit.com/chrisveness/crypto/master/sha1.js) instead of [this](https://github.com/matteobrusa/Password-protection-for-static-pages/blob/master/index.html#L87)), which has a syntax error. And in turn, when you submit the password, you're calling a function which is not referenced.

<img width="507" alt="Bildschirmfoto 2019-03-13 um 20 38 00" src="https://user-images.githubusercontent.com/845131/54309473-7e8a0780-45d0-11e9-9597-b50e74b8553e.png">

<img width="460" alt="Bildschirmfoto 2019-03-13 um 20 43 14" src="https://user-images.githubusercontent.com/845131/54309724-040db780-45d1-11e9-9953-70a8d9cf888d.png">

**Changing the source for the SHA1 script should fix your problem.**
